version: '3.8'
services:
  logstash:
    build: ./logstash
    container_name: logstash
    volumes:
      - ./logstash/data:/usr/share/logstash/data
      - ./logstash/input:/usr/share/logstash/input
      - ./logstash/output:/usr/share/logstash/output
      - ./logstash/logs:/usr/share/logstash/logs
    stdin_open: true
    tty: true
