# Chemin vers le dossier de data
path.data: "./data"

# Si les évènements en sortie doivent-être ordonné ou non
pipeline.ordered: true

# Desactivation de la compatibilité ECS
pipeline.ecs_compatibility: disabled

# Log level
log.level: info

# Nombre de worker pour pour chaque pipeline
pipeline.workers: 1

# Chemin vers les fichiers de logs
path.logs: "./logs"
